"""Wind and visibility from the Open-Meteo Forecast API.

WHY A SECOND CLIENT EXISTS: the marine endpoint this app already calls
(marine-api.open-meteo.com/v1/marine) carries waves, swell and sea-surface
temperature but NO wind speed — verified against the current Open-Meteo marine
docs on 2026-07-30. Its `wind_wave_*` parameters describe waves generated by
wind, not the wind itself. Atmospheric wind lives on a different host
(api.open-meteo.com/v1/forecast), so a condition brief that mentions wind needs
this call. Parameter names were read from the docs, not guessed:
  wind_speed_10m (km/h default), wind_direction_10m, wind_gusts_10m, visibility

Caching, degradation and the never-raise contract deliberately mirror
services/marine/client.py so both halves of a brief behave the same way, and so
`stale`/`cached`/`mock` mean the same thing across the app.

No API key. Non-commercial use, same as the marine endpoint.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timedelta, timezone

import httpx
from sqlmodel import Session, select

from app.core.config import get_settings
from app.models.entities import MarineForecastCache

log = logging.getLogger(__name__)

FORECAST_API_BASE = "https://api.open-meteo.com/v1/forecast"
HOURLY_VARS = "wind_speed_10m,wind_direction_10m,wind_gusts_10m,visibility"

# Reuses MarineForecastCache with a distinct key prefix rather than adding a
# table: same 30-minute freshness policy, no migration, and one place to look
# when debugging a stale brief.
_KEY_PREFIX = "wind:"


def _location_key(lat: float, lon: float) -> str:
    return f"{_KEY_PREFIX}{round(lat, 2)},{round(lon, 2)}"


def _summarise(payload: dict) -> dict:
    hourly = payload.get("hourly", {})
    times = hourly.get("time", [])
    if not times:
        return {}
    idx = 0
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:00")
    if now_iso in times:
        idx = times.index(now_iso)

    def val(name: str):
        vals = hourly.get(name) or []
        return vals[idx] if idx < len(vals) else None

    return {
        "time": times[idx],
        # The grid point the forecast model answered for; see the marine client.
        "grid_latitude": payload.get("latitude"),
        "grid_longitude": payload.get("longitude"),
        "wind_speed_kmh": val("wind_speed_10m"),
        "wind_direction_deg": val("wind_direction_10m"),
        "wind_gusts_kmh": val("wind_gusts_10m"),
        "visibility_m": val("visibility"),
    }


def deterministic_mock(lat: float, lon: float) -> dict:
    """Labelled fallback so a brief can still render with no network. Always
    surfaces as data_kind="sample"/mock — never presented as an observation."""
    seed = int(abs(lat * 100) + abs(lon * 100)) % 7
    return {
        "time": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:00"),
        "wind_speed_kmh": round(14.0 + seed * 2.5, 1),
        "wind_direction_deg": 110 + seed * 8,
        "wind_gusts_kmh": round(22.0 + seed * 3.0, 1),
        "visibility_m": 24000 - seed * 800,
    }


def get_wind_conditions(session: Session, lat: float, lon: float,
                        allow_network: bool = True) -> dict:
    """Wind + visibility for one point. Never raises.

    Degrades live -> fresh cache -> stale cache -> deterministic mock, labelling
    each with `cached`, `stale` and `mock` so the caller can set data_kind
    honestly rather than assuming freshness.
    """
    settings = get_settings()
    key = _location_key(lat, lon)
    cached = session.exec(
        select(MarineForecastCache)
        .where(MarineForecastCache.location_key == key)
        .order_by(MarineForecastCache.fetched_at.desc())  # type: ignore[union-attr]
    ).first()
    fresh_until = datetime.now(timezone.utc) - timedelta(minutes=settings.marine_cache_minutes)

    def _naive(dt: datetime) -> datetime:
        return dt.replace(tzinfo=None) if dt.tzinfo else dt

    if cached and _naive(cached.fetched_at) > _naive(fresh_until):
        data = json.loads(cached.payload_json)
        data.update({"stale": False, "cached": True})
        return data

    if allow_network:
        url = (f"{FORECAST_API_BASE}?latitude={lat}&longitude={lon}"
               f"&hourly={HOURLY_VARS}&forecast_days=1")
        for _attempt in range(2):  # bounded retry, same as the marine client
            try:
                r = httpx.get(url, timeout=10)
                r.raise_for_status()
                summary = _summarise(r.json())
                if summary:
                    data = {
                        "location": key, "source": "open-meteo-forecast",
                        "attribution": "Weather data by Open-Meteo.com (CC-BY 4.0)",
                        "mock": False, **summary,
                    }
                    session.add(MarineForecastCache(location_key=key, payload_json=json.dumps(data)))
                    session.commit()
                    data.update({"stale": False, "cached": False})
                    return data
            except (httpx.HTTPError, ValueError, KeyError):
                continue

    if cached:  # offline: a stale real reading beats a fabricated one
        data = json.loads(cached.payload_json)
        data.update({"stale": True, "cached": True})
        return data

    return {
        "location": key, "source": "deterministic-mock",
        "attribution": "Deterministic demonstration values (not a real forecast)",
        "mock": True, "stale": False, "cached": False,
        **deterministic_mock(lat, lon),
    }
