"""Mandatory disclosure strings. Injected server-side; the model cannot remove them."""

PERMANENT_LIMITATION = (
    "Lamer Konekte provides AI-assisted catch documentation and informational "
    "guidance. Species suggestions and regulatory checks must be confirmed against "
    "official sources and by the fisher or an authorised officer."
)

MARINE_DISCLAIMER = (
    "Marine forecasts are informational and may be incomplete near the coast. "
    "Confirm conditions through official local marine advisories before travelling."
)

RULE_VERIFY_NOTICE = "Verify against the latest official fisheries notice."

MOCK_DISCLOSURE = (
    "Demonstration mode: this response was generated by a deterministic offline mock, "
    "not by a Gemma model."
)

FALLBACK_DISCLOSURE = (
    "The hosted Gemma service was unavailable; this response fell back to the "
    "deterministic offline mock and is not real model inference."
)
